### PR TITLE
Add support for ssh command line options

### LINKED ISSUE #1: Ability to specify additional command line options
Consider adding ssh command line options to configuration file. E.g.:

``` json
{
    "targets": [
        {
            "host": "user@example-machine.local",
            "friendly": "This is an example target",
            "options": {
                "p": "443",
                "vvv": "",
                "1": ""
            }
        }
    ]
}
```

will execute `ssh user@example-machine.local -p443 -vvv -1`

### PR DESCRIPTION
**Pull request by RealJTG**
Fixes #1 
Adds "options" configuration key

``` json
{"targets": [
    {
        "friendly": "altssh dev server available behind firewall",
        "host": "user@dev.alt",
        "options": {
            "p": "443"          
        }
    }
]}
```

Will execute `ssh user@test.dev -p 443`

### CODE REVIEW

**Comment by mmeyer724** [comment]
Hi,

First off, thank you for the contribution! I do have a few small suggestions, let me know what you think.
- Since not all command line options require a value be provided, like `-vvv`, or might be more complicated than `-{option}{value}`, consider changing the configuration to look like this:

```
{  
   "targets":[  
      {  
         "friendly":"altssh dev server available behind firewall",
         "host":"user@dev.alt",
         "options":[  
            "-p443",
            "-vvv"
         ]
      }
   ]
}
```

If we do this, I believe we can also use `os.execvp(file, args)` to avoid unpacking the options (I haven't played around with this at all).
- Update example/default configuration and readme.rst to reflect the new configuration (additionally including a few example options)

Otherwise, this looks like a very useful addition. I very recently had the need to add a target with a non-standard port, but I never wrote out the code for it, so this is pretty good timing for me.

**Comment by RealJTG** [comment]
Yep, sounds reasonable.

**Comment by RealJTG** [comment]
Done. Also moved command line options between "ssh" and "hostname" where they sould be (otherwise user may accidentally execute option without dash as command on remote host) and added indentation to newly created config file.

**Comment by mmeyer724** [comment]
Nice! I'm going to test it out myself quickly, will comment back/merge afterwards.

**Comment by mmeyer724** [comment]
Tagged in 0.0.2, release pushed to pypi + homebrew formula updated.

Thanks!

**Pull request merged**
